### PR TITLE
Option to use DataCache, exposed more cache helper methods

### PR DESCRIPTION
**Pull request by Zalkovalsky**
- Added option to setup `ImagePipeline` with data cache (on disk)
- A couple of new methods to:
  - check if an image is in cache (all layers)
  - get an `UIImage` directly 
  - remove specific image from caches
  - clean all cache layers
- More options added to the sample project
- Typo in readme

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Neat! Will check this out :)

**Comment by Zalkovalsky** [comment]
There seems to be some issue with `Carthage`, I see it locally as well. `Carthage/Build` is not always created when running `sh carthage.sh update --use-xcframeworks`, sometimes it just creates the directory for mac-os target. It does get resolved after you run it couple of times 🤷‍♂️

**Comment by Zalkovalsky** [comment]
> There seems to be some issue with `Carthage`, I see it locally as well. `Carthage/Build` is not always created when running `sh carthage.sh update --use-xcframeworks`, sometimes it just creates the directory for mac-os target. It does get resolved after you run it couple of times 🤷‍♂️

This seems like a blimp, running this 2nd time did the trick 😅

**Comment by Cheesebaron** [comment]
Just gave this a spin. Getting this error on startup of the sample app:
```

2023-01-04 08:28:51.258214+0100 Sample[64521:1215394] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[ImagePipeline setupWithDataCache]: unrecognized selector sent to class 0x10b2054d8'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010cd048cb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010c530ba3 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010cd139f1 __CFExceptionProem + 0
	3   CoreFoundation                      0x000000010cd08d91 ___forwarding___ + 1431
	4   CoreFoundation                      0x000000010cd0b088 _CF_forwarding_prep_0 + 120
	5   libxamarin-dotnet.dylib             0x000000010bf42649 xamarin_dyn_objc_msgSend + 217
	6   ???                                 0x000000013f5f7547 0x0 + 5358187847
```

**Review by Cheesebaron — APPROVED** [review]

**Pull request merged**
